### ISSUE TITLE
multiple structures on the same tile 

### ISSUE THREAD

**Issue by atg-abhishek** [EmilyRSager/MedeivalWarfare#4]
Tree Growth Phase: This phase occurs at the beginning of each round (except for the very first round). For each
tree tile, an adjacent empty or meadow tile is picked randomly and a new tree is created on that tile with a 50%
probability. If there are no adjacent empty or meadow tiles (i.e. all adjacent tiles are either sea tiles, other trees,
villages, structures, roads, or occupied by villagers) then no additional tree is created on this turn for that tree.

Based on the above text do you think that a tile can have a tree with a meadow on it ?? i.e. it will have two structures on it, right now the way we have it setup is that its an enum so we can only have a single value of struct type for each tile

**Comment by itscharlieb** [comment]
Not sure about this, very ambiguous from the description whether the tree would replace the meadow or coexist. Something to be cleared up with Joerg. Although with the current implementation, a meadow is not a structure type but rather a boolean field in tile, so there should be no problem having both.

**Comment by atg-abhishek** [comment]
Ok yes that works for the time being , we could ask joerg about this, it
seems very ambiguous to me too
