### ISSUE TITLE
ReaderThread.java 

### ISSUE THREAD

**Issue by atg-abhishek** [EmilyRSager/MedeivalWarfare#6]
for the cleanup() function shouldn't it be in a finally block ? i think syntactically that is correct rather than it floating outside ....

**Comment by itscharlieb** [comment]
The reason it is not inside the catch block is that the method should be called when the 'isRunning' flag is set to false. Later on when we support gracefully shutting down connections, the ServerChannel assosiacted with an exiting reader thread can call 'shutDown' on the readerThread. At least that was the idea. But it provides no use right now cuz we never call shutDown, we just let the thread be interrupted when a client disconnects.

**Comment by itscharlieb** [comment]
Oh but you said finally block. Yes, it should be in a finally block

**Comment by itscharlieb** [comment]
Disregard my earlier comments if you saw them, yes we can put that inside a finally block.

**Comment by atg-abhishek** [comment]
Cool :)
